### ISSUE TITLE
Misspelled LogManager.getLogger() argument: "Comand Relay" instead of "Command Relay"

### ISSUE THREAD

**Issue by ilovapples** [DcmanProductions/Command-Relay-Mod#1]
In [`common/src/main/java/chase/minecraft/architectury/commandrelay/CommandRelay.java`](https://github.com/DcmanProductions/Command-Relay-Mod/blob/master/common/src/main/java/chase/minecraft/architectury/commandrelay/CommandRelay.java#L10), the argument to `LogManager.getLogger()` is `"Comand Relay"` instead of `"Command Relay"`. This could cause the logging to not work properly.

**Comment by Drew-Chase** [comment]
Thanks, I totally missed that!
